/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2025-05-12 04:34:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Menu</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Arial', sans-serif;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("  background: url('images/image5.jpg') no-repeat center center/cover; \r\n");
      out.write("    color: #333;\r\n");
      out.write("    line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-header {\r\n");
      out.write("    background-color: red;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 20px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-header h1 {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    font-size: 2.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Menu Container */\r\n");
      out.write(".menu-container {\r\n");
      out.write("    max-width: 800px;\r\n");
      out.write("    margin: 20px auto;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Section Styles */\r\n");
      out.write(".menu-section {\r\n");
      out.write("    margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-section h2 {\r\n");
      out.write("    font-size: 1.8em;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    border-bottom: 2px solid #007BFF;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    color: #007BFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item {\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    padding-bottom: 10px;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item h3 {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 1.2em;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item h3 span {\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #007BFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item p {\r\n");
      out.write("    margin: 5px 0 0 0;\r\n");
      out.write("    font-size: 0.9em;\r\n");
      out.write("    color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 600px) {\r\n");
      out.write("    .menu-container {\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu-header h1 {\r\n");
      out.write("        font-size: 2em;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu-section h2 {\r\n");
      out.write("        font-size: 1.5em;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .menu-item h3 {\r\n");
      out.write("        font-size: 1em;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write(".home-button {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: 12px 20px;\r\n");
      out.write("    background-color: #4a90e2;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"menu-header\">\r\n");
      out.write("        <h1>Restaurant Menu</h1>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"menu-container\">\r\n");
      out.write("        <!-- Appetizers Section -->\r\n");
      out.write("        <section class=\"menu-section\">\r\n");
      out.write("            <h2>Appetizers</h2>\r\n");
      out.write("            <div class=\"menu-item\">\r\n");
      out.write("                <h3>Spring Rolls <span>₹ 300</span></h3>\r\n");
      out.write("                <p>Fresh vegetables wrapped in rice paper, served with sweet chili sauce.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-item\">\r\n");
      out.write("                <h3>Garlic Bread <span>₹ 500</span></h3>\r\n");
      out.write("                <p>Warm, crusty bread topped with garlic butter and herbs.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Main Course Section -->\r\n");
      out.write("        <section class=\"menu-section\">\r\n");
      out.write("            <h2>Main Course</h2>\r\n");
      out.write("            <div class=\"menu-item\">\r\n");
      out.write("                <h3>Grilled Salmon <span>₹ 600</span></h3>\r\n");
      out.write("                <p>Freshly grilled salmon with a lemon butter sauce and steamed vegetables.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-item\">\r\n");
      out.write("                <h3>Mutton  <span>₹ 450</span></h3>\r\n");
      out.write("                <p>Succulent beef steak served with mashed potatoes and gravy.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Desserts Section -->\r\n");
      out.write("        <section class=\"menu-section\">\r\n");
      out.write("            <h2>Desserts</h2>\r\n");
      out.write("            <div class=\"menu-item\">\r\n");
      out.write("                <h3>Chocolate Lava Cake <span>₹ 350</span></h3>\r\n");
      out.write("                <p>Rich chocolate cake with a molten chocolate center.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu-item\">\r\n");
      out.write("                <h3>Cheesecake <span>₹ 650</span></h3>\r\n");
      out.write("                <p>Creamy cheesecake served with a strawberry topping.</p>\r\n");
      out.write("\r\n");
      out.write("<a href=\"home.jsp\" class=\"home-button\" >Go to Home</a>            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
